### ISSUE TITLE
Infer requirements from imports

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/coherent.build#3]
How nice would it be if dependencies could be inferred from the source code? Other non-public projects have achieved this with success (across languages).

**Comment by pawamoy** [comment]
Digged up from my [stars](https://github.com/pawamoy/stars), some projects we could take inspiration (or code) from:

- https://github.com/fpgmaas/deptry: Find unused, missing and transitive dependencies in a Python project. 
- (shameless plug) https://github.com/pawamoy/dependenpy: Show the inter-dependencies between modules of Python packages. 

dependenpy is meant for dependencies between modules, but it actually scans all imports.

I guess that we should really write our own AST visitor to handle conditions on Python versions to infer the right markers :slightly_smiling_face:

**Comment by jaraco** [comment]
Initial indicators are that an LLM can do this work well. I asked Gemini for a basic result and it came up with the right answer:

![image](https://github.com/coherent-oss/coherent.build/assets/308610/a3527d19-1b43-4a22-8496-c73a0f310ec0)

I had to paste a screenshot as the "share" button isn't working currently.

**Comment by pawamoy** [comment]
Nice. I wonder how well it performs for projects that have non equal distribution and package name.

I do have to say though that I think it's easily solved with code and shouldn't need LLMs. Querying a LLM for each build would feel wasteful IMO. Not sure if this was your idea or if you had something else in mind :)

EDIT: Maybe not so easily solved for the same reason: projects that have different dist/package names ^^

**Comment by jaraco** [comment]
I chose `attr` because the distribution name is `attrs` (subtle, but different).

**Comment by pawamoy** [comment]
Ah right, I didn't know it was different :+1:

**Comment by jaraco** [comment]
In 8b577b2, I connected the Gemini-backed import inference. At first blush, I was impressed. It detected `requests` and `google-generativeai` as dependencies. But then I ran it on `discovery.py`, and it failed with:

```
["dateutil", "jaraco.context", "jaraco.functools", "packaging", "pip-run", "requests", "setuptools-scm"]
```

That's mostly good, but `dateutil` isn't the distribution name. It's `python-dateutil`.

And it failed on `bootstrap.py`, finding `['pathlib']` as a requirement. And on `__main__.py`, it found `['runpy']`. It apparently doesn't even know when an import is from the stdlib. Even worse, on `__init__.py`, it read the requirements out of `__requires__`... maybe not a big surprise, but incorrect nonetheless.

So I'm convinced Gemini is not up to the task. Some have suggested Claude, so I'll try that and see if it's any better. If not, I'll abandon the AI approach for a more direct approach.

**Comment by jaraco** [comment]
Claude does a little better. It at least recognizes that `python-dateutil` is needed for `dateutil` (although only when writing the requirements.txt and not when identifying the dependencies). Unfortunately, it fails to identify `jaraco.context` as a dependency.

![image](https://github.com/coherent-oss/coherent.build/assets/308610/c7cc2c4a-063a-49b5-9953-045084d4f242)

**Comment by jaraco** [comment]
Since the gemini model seems more complete, it occurs to me that I could include things in the prompt to help keep it on the right track. Hints like "don't forget that `dateutil` is supplied by the `python-datetime` package."

**Comment by jaraco** [comment]
In 909ce57, I tried that, but the model continued to emit `dateutil` and started emitting `python-dateutil` for modules that had no related imports.

**Comment by zsol** [comment]
I think a key part here is that it's impossible to get this 100% right globally, so we'll need to find (project-specific) ways of hinting the system towards the right solution. In the systems I've seen a comment on the import is generally effective:

```
from dateutil import *  # pkg:pypi/python-dateutil
```

Then once we have a reasonably ergonomic way of hinting, the goal of the system would be to minimize the amount of hints required.

**Comment by pawamoy** [comment]
What about privacy? Or concerns about LLMs? IMO instead of querying LLMs we should instead search for a maintained map of `package name` to `distribution name`, or build such a map ourselves. Most projects have equal distribution and package name, surely it wouldn't be hard to update the map from time to time when there's a mismatch? We only have to keep track of the projects for which package and distribution names are different.

**Comment by pawamoy** [comment]
Erm, every question and answer I can find on the web all assume the packages are already installed on disk... Easy to get package name from dist name by querying pypi, but not the reverse.

**Comment by pawamoy** [comment]
Might be possible to scrape https://pypi.org/search/?q=dateutil to get relevant dists, then check their metadata to find one that provides a `dateutil` package. It wouldn't prevent incorrect results though, as any dist can provide any package name.

**Comment by pawamoy** [comment]
Anyway, there will always be cases when we can't infer the right distribution name, and LLMs won't do better. For example when I use a recent fork (published to PyPI) that didn't change the package name. So @zsol's suggestion is probably the best thing we can do.

**Comment by johnslavik** [comment]
I think any use of LLMs isn't guaranteed to be deterministic.
It would be a good idea to split the explored ideas into categories of deterministic and non-deterministic and prefer deterministic solutions for most cases. @zsol's suggestion is a very deterministic solution and I'm a huge fan of that approach—even though it's not necessarily "inferring" requirements then, but hinting, as he said. A modest problem is, annotating this near imports makes it possible for these comments to diverge in different imports from packages of the same name, e.g.
```py
# ./foo.py
import dotenv  # pkg:pypi/dotenv
```

```py
# ./bar.py
import dotenv  # pkg:pypi/python-dotenv
```

**Comment by jaraco** [comment]
> Might be possible to scrape https://pypi.org/search/?q=dateutil to get relevant dists, then check their metadata to find one that provides a `dateutil` package. It wouldn't prevent incorrect results though, as any dist can provide any package name.

I had a similar idea - what if we scanned all packages from PyPI, ranked them by popularity, and then examined them to see what top-level names they expose (imports they satisfy). Then store these in a database keyed on those top-level names.

This would map `dateutil` → `python-dateutil` and `pkg_resources` → `setuptools`, and `jaraco.context` (but not `jaraco.functools`) → `jaraco.context`. It would map `dotenv` to the most popular package (since ambiguous), and maybe warn about the ambiguity. Hints or explicit dependencies could be employed to override incorrect inference or silence warnings.

Perhaps this functionality could be contributed back to warehouse such that it eventually is available in the warehouse API (or at least the mapping of exposed top-level names could be queried from the API).

**Comment by johnslavik** [comment]
> It would map dotenv to the most popular package (since ambiguous), and maybe warn about the ambiguity. 

99% cases of ambiguity could be resolved by comparing the usage of the exported APIs of competing libraries (e.g. `python-dotenv` exports different names than `dotenv`). But that would involve some static analysis, which is tricky to get right and probably too costly for this sort of problem.

**Comment by jaraco** [comment]
> Digged up from my [stars](https://github.com/pawamoy/stars), some projects we could take inspiration (or code) from:
> 
>     * https://github.com/fpgmaas/deptry: Find unused, missing and transitive dependencies in a Python project.


I took a look at deptry. It's heavily reliant on parsing a PEP 621 pyproject.toml file, suggesting it's strongly coupled to the concept of statically-declared dependencies. It also requires the examined project to be installed into a virtual environment, suggesting that it's not doing any static analysis. I don't yet understand why it needs the project to be installed.

It still may be worthwhile examining the implementation to see if any of its internals could be re-purposed for extracting imports or mapping them to distribution packages.

>     * (shameless plug) https://github.com/pawamoy/dependenpy: Show the inter-dependencies between modules of Python packages.
> 
> dependenpy is meant for dependencies between modules, but it actually scans all imports.

It looks like this also relies on runtime analysis. Does it have any functionality for static analysis of imports?

> I guess that we should really write our own AST visitor to handle conditions on Python versions to infer the right markers 🙂

I wonder if there's already some functionality in the type checkers or linters that could help here. I'll probably delay investigation of conditional imports or programmatic imports for an initial implementation (just assume all import statements are relevant).

**Comment by pawamoy** [comment]
> It looks like this also relies on runtime analysis. Does it have any functionality for static analysis of imports?

It actually relies solely on static analysis. However it does expect package names as input, and to find the sources it scans folders in sys.path (IIRC), so generally speaking packages must be "installed".

**Comment by jaraco** [comment]
In the [feature/import-detection branch](https://github.com/coherent-oss/coherent.build/tree/feature/import-detection), I've started work on import detection. The current implementation only performs extraction of non-standard imports from a given module, but it does appear to be working well without too much code:

```
 coherent.build feature/import-detection 🐚 py -m imports discovery.py
['jaraco.functools', 'jaraco.vcs', 'packaging.requirements', 'requests', 'setuptools_scm', 'jaraco.compat.py38.r_fix', 'jaraco.context.suppress', 'packaging.version.Version', 'pip_run.scripts']
```

Next step would be to build the mapping of those imports to their distributions and to write a routine that accumulates the imports across all modules in the source.

**Comment by jaraco** [comment]
In the latest commit, I've added a script that gets to 95%+ of the packages. Here's [what it emitted](https://gist.github.com/jaraco/8c2c6c54a618c821ea038635887762a5) on stdout on the last run.

I'm sure there are still some edge cases and issues to address, including:

- [x] Recognizes implicit namespace packages, but doesn't recognize pkgutil or pkg_resources namespaces.
- [x] Some packages in the first few hundred fail with errors. These errors are probably ignorable.
- [x] Names emitted are the PEP 502 normalized names. We'll want to extract the actual project name from the metadata.
- [x] We'll want some way to cache/save the values, perhaps to a database, so the work can be re-used across runs.

**Comment by pawamoy** [comment]
```
{"pyarrow": ["benchmarks", "pyarrow", "examples.dataset.write_dataset_encrypted", "examples.flight.client", "examples.flight.middleware", "examples.flight.server", "examples.parquet_encryption.sample_vault_kms_client", "scripts.run_emscripten_tests", "scripts.test_imports", "scripts.test_leak"]}
```

:speak_no_evil: 

---

Nice!

> Recognizes implicit namespace packages, but doesn't recognize pkgutil or pkg_resources namespaces.

Here's how we tell if a package is a pkg-style (pkg-util/pkg-resources) namespace package in Griffe:

```python
_re_pkgresources = re.compile(r"(?:__import__\([\"']pkg_resources[\"']\).declare_namespace\(__name__\))")
_re_pkgutil = re.compile(r"(?:__path__ = __import__\([\"']pkgutil[\"']\).extend_path\(__path__, __name__\))")

# TODO: For more robustness, we should load and minify the AST
# to search for particular call statements.
def _is_pkg_style_namespace(init_module: Path) -> bool:
    code = init_module.read_text(encoding="utf8")
    return bool(_re_pkgresources.search(code) or _re_pkgutil.search(code))
```

(looking at the regular expressions again, I'm not sure why I wrap the whole expressions into non-captured groups :thinking:)

Not the most robust as the TODO comment shows, but in practice the docs state that these "exact" lines should be used, so it probably supports ~95% of pkg-style namespace packages in the wild.

> We'll want some way to cache/save the values, perhaps to a database, so the work can be re-used across runs.

Are you thinking online, global DB or something like a local cache?

**Comment by jaraco** [comment]
I'm thinking a global DB, since it's reflecting the global dataset of public Python packages.

**Comment by jaraco** [comment]
In 2efaba3, the inference now excludes namespace packages.

Before

```
 coherent.build 2649f76 🐚 pip-run -- top-distributions.py -i backports.tarfile
{"norm_name": "backports-tarfile", "name": "backports.tarfile", "roots": ["backports"]}
```

After

```
 coherent.build feature/import-detection 🐚 pip-run -- top-distributions.py -i backports.tarfile
{"norm_name": "backports-tarfile", "name": "backports.tarfile", "roots": ["backports.tarfile"]}
```

**Comment by jaraco** [comment]
In 71f3e43, I've put together a hacky means of loading from or persisting to a mongoDB collection the details of the analysis. The good news is that change provides an efficiently-queryable view of the dataset (by the import roots). Of the 8000 most popular packages, it was able to load 7130 roots. That seems like a reasonable, if not slightly low coverage of the space.

Right now, only I have access to the database, but I'm pleased to report that the DB takes up 794kB, and the indexes about ~1MB (the roots index consuming the bulk at 635kB), so just a few MB is enough to service this need.

Next, I'd like to:

- [x] Make the database world-readable
- [x] Provide a routine to query the database to resolve roots to distributions.
- [x] Provide a routine requiring write access to refresh the dataset (essentially what's already done).

**Comment by jaraco** [comment]
In 7b538cdb53ce318323f6c350efe51dd66dfd12b3 and 806f5182e5aeb6e29b8506917e9875a378cc24f7, I've added support for anyone to query the database. If you're feeling like exploring the database, consider grabbing the [Compass](https://www.mongodb.com/try/download/compass) app and connect using the connection URI: 

```
mongodb+srv://anonymous:coherent.build@cluster0.acvlhai.mongodb.net/
```

**Comment by jaraco** [comment]
In 32f561cfcef5e65a0d819e94aab419dbc885452d...ff0316bab0fd2a83f3e7fcfe6247f82dcab221dc, I've added a routine that ties it all together and comes pretty close to inferring the raw dependencies needed:

```
>>> list(discovery.inferred_deps())
Error resolving import jaraco.compat.py38.r_fix
Error resolving import jaraco.functools.pass_none
Error resolving import wheel.wheelfile.WheelFile
Error resolving import jaraco.vcs
Error resolving import packaging.requirements
Error resolving import jaraco.compat.py38.r_fix
Error resolving import jaraco.context.suppress
Error resolving import packaging.version.Version
Error resolving import pip_run.scripts
Error resolving import zipp.compat.overlay.zipfile
Error resolving import jaraco.mongodb.helper
Error resolving import tempora.utc
Error resolving import more_itertools.first
Error resolving import more_itertools.one
Error resolving import requests_toolbelt.sessions
['packaging', 'jaraco.functools', 'requests', 'setuptools-scm', 'jaraco.context', 'keyring', 'autocommand']
```

I still need to figure out how to:

- [x] Resolve a submodule to its parent module (i.e. `pip_run.scripts` → `pip_run` or `jaraco.functools.pass_none` → `jaraco.functools`).
- [x] Handle submodules of the local package (e.g. `coherent.build.compat*`)
- [x] Handle modules in the `tests` directory (and associate them with the `test` extra).

**Comment by jaraco** [comment]
In 009e1e5, the routine now resolves submodules to parents and takes the first one that resolves. This approach now resolves even more packages:

```
>>> list(discovery.inferred_deps())
Error resolving import jaraco.compat.py38.r_fix
Error resolving import jaraco.vcs
Error resolving import jaraco.compat.py38.r_fix
Error resolving import pip_run.scripts
Error resolving import jaraco.mongodb.helper
['packaging', 'jaraco.functools', 'wheel', 'jaraco.functools', 'packaging', 'requests', 'setuptools-scm', 'jaraco.context', 'packaging', 'jaraco.context', 'zipp', 'keyring', 'tempora', 'more-itertools', 'more-itertools', 'requests-toolbelt', 'autocommand']
```

It's interesting that it's still failing to resolve a small number of them. Is that just because they're not in the database?

**Comment by jaraco** [comment]
Indeed, all that was needed was to ensure those packages were in the database:

```
>>> from coherent.build import pypi
>>> dist = pypi.Distribution('pip-run')
>>> dist.load()
>>> dist.save()
>>> dist = pypi.Distribution('jaraco.vcs')
>>> dist.load()
>>> dist.save()
>>> dist = pypi.Distribution('jaraco.compat')
>>> dist.load()
>>> dist.save()
>>> dist = pypi.Distribution('jaraco.mongodb')
>>> dist.load()
>>> dist.save()
>>> from coherent.build import discovery
>>> list(discovery.inferred_deps())
['packaging', 'jaraco.compat', 'jaraco.functools', 'wheel', 'jaraco.functools', 'jaraco.vcs', 'packaging', 'requests', 'setuptools-scm', 'jaraco.compat', 'jaraco.context', 'packaging', 'pip-run', 'jaraco.context', 'zipp', 'jaraco.mongodb', 'keyring', 'tempora', 'more-itertools', 'more-itertools', 'requests-toolbelt', 'autocommand']
```

**Comment by jaraco** [comment]
In f54b355, the routine now handles all sources.

**Comment by jaraco** [comment]
I've expanded the space to search. It looks like there are < 800,000 packages in PyPI, so I'm indexing them all. To do so, I downloaded the full set of "top" packages by installing pypinfo and then running:

```
pipx run pypinfo --json --indent 0 --limit 800000 --days 30 "" project > top-pypi-packages-30-days.json
```

I've also refactored the code to inject database entries even for those with errors, so I can do a query like `{ error: { $exists: true, $ne: "No wheels" } }` and find records like:

```json
{
  "_id": {
    "$oid": "66c8521be741073f6b05d51c"
  },
  "id": "smartapi-python",
  "error": "'utf-8' codec can't decode byte 0xc1 in position 8: invalid start byte",
  "updated": {
    "$date": "2024-08-23T09:10:51.830Z"
  }
}
```

I did some investigation and it turns out that package has a `test` package whose `__init__.py` looks like a rarfile header:

```
 🐚 hexdump test/__init__.py
0000000 6152 2172 071a 0001 dfc1 565f 0103 0004
0000010 771d 5156 0503 0004                    
0000018
```

Those bytes resolve to `Rar!�¡ﬂ_V�wVQ�`.

It's an empty rarfile:

```
 🐚 unrar l test/__init__.py

UNRAR 7.01 freeware      Copyright (c) 1993-2024 Alexander Roshal

Archive: test/__init__.py
Details: RAR 5
  0 files
```

When `coherent.build.pypi.is_namespace` attempts to read that file, it fails to decode it as utf-8. I'm thinking to just suppress that error, since it's unlikely that any file that's not decodable as utf-8 will be a namespace package `__init__`.

**Comment by jaraco** [comment]
Another issue I encountered today: the `ks-utility` wheel seems to be somewhat corrupt. If I install the wheel using pip, it extracts fine and there's an empty `ks_utility/__init__.py` file in the output, but if I open the wheel using `zipfile`, that entry is listed, but attempting to `open` it results in a `KeyError`:

```python
>>> 'ks_utility/__init__.py' in dist.wheel.root.namelist()
True
>>> dist.wheel.root.open('ks_utility/__init__.py')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1604, in open
    zinfo = self.getinfo(name)
            ^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/zipp/__init__.py", line 190, in getinfo
    return super().getinfo(name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/zipfile/__init__.py", line 1532, in getinfo
    raise KeyError(
KeyError: "There is no item named 'ks_utility/__init__.py' in the archive"
```

How can it be there and not be there at the same time?

Doesn't matter - just need to figure out where/how to handle that sort of error.

**Comment by jaraco** [comment]
I keep running into these ChunkedEncodingErrors:

```
 🐚 py -m coherent.build.load-distributions --url file:///Users/jaraco/Downloads/top-pypi-packages-30-days.
json --skip @(9174+4840+1000+42145+6548+1376+3496+11130+4961)
  3%|██▉                                                                                                 | 13505/452639 [45:50<24:50:43,  4.91it/s]
Unhandled exception processing {"id": "fastanpr"}
Traceback (most recent call last):
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/urllib3/response.py", line 748, in _error_catcher
    yield
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/urllib3/response.py", line 894, in _raw_read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions.IncompleteRead: IncompleteRead(4194304 bytes read, 1487925 more expected)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/urllib3/response.py", line 1060, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/urllib3/response.py", line 977, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/urllib3/response.py", line 872, in _raw_read
    with self._error_catcher():
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/urllib3/response.py", line 772, in _error_catcher
    raise ProtocolError(arg, e) from e
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(4194304 bytes read, 1487925 more expected)', IncompleteRead(4194304 bytes read, 1487925 more expected))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jaraco/code/coherent-oss/coherent.build/load-distributions.py", line 14, in <module>
    @autocommand.autocommand(__name__)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/.local/pip-run/autocommand/autocommand.py", line 66, in autocommand_decorator
    func = automain(module)(func)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/.local/pip-run/autocommand/automain.py", line 55, in automain_decorator
    sys.exit(main(*args, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/.local/pip-run/autocommand/autoparse.py", line 301, in autoparse_wrapper
    return func(*parsed_args.args, **parsed_args.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/load-distributions.py", line 29, in run
    dist.load() or dist.save()
    ^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/pypi.py", line 127, in load
    doc = found or self.from_wheel()
                   ^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/pypi.py", line 137, in from_wheel
    name=self._get_name(),
         ^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/pypi.py", line 148, in _get_name
    info = one(self.wheel.glob('*.dist-info'))
               ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/pypi.py", line 114, in wheel
    resp = session.get(match['url'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/requests_toolbelt/sessions.py", line 76, in request
    return super(BaseUrlSession, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaraco/code/coherent-oss/coherent.build/.venv/lib/python3.12/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(4194304 bytes read, 1487925 more expected)', IncompleteRead(4194304 bytes read, 1487925 more expected))
```

In 9ed83f6, I added retry support, but the failures persist, so I just keep manually restarting. I don't know what else to do.

**Comment by jaraco** [comment]
After lots of failures and restarts, I've realized there's a better way. We can do a two-phase import. The first phase loads the distribution ids from the "top distributions" into the database without any processing of wheels. Then a separate routine can query the database for unprocessed (or stale) distributions and re-process the wheel. The first phase will be robust and completed very quickly, and the second phase can be restarted at any time easily.

That's what I've started in 9ed83f6...00efa60. I still need to add the "process" routine.

**Comment by jaraco** [comment]
In the latest commit (a058dc7), I've added a routine to process the unprocessed records (of which there are currently 315k). It processes them at a rate of about 6/sec, but once it's done one pass through, we'll have a decent snapshot of the state of modules available in PyPI, and we can explore relying on that as a source of truth for discovering dependencies.

I'm thinking I'll probably move this functionality to another library (`coherent.distributions` maybe?) so that other projects can make use of it as well.

**Comment by jaraco** [comment]
Oh wow. I just realized something amazing about coherent and the essential layout. If I want to split this project into two, I just need to cherry-pick (or filter) the commits that affect the relevant modules (in this case, `pypi.py`, `*-distributions.py`, and `__init__.py` (for dependencies)) into a new repository, and it's ready to go. No relocation is necessary, no metadata needs to be updated. It also means that I don't have to be careful about what name to pick. If I chose `coherent.distributions` and later decide I want `coherent.dists`, all I have to do to change it is rename the repo. Everything else derives from that.

Oh, there is one concern - the `__init__.py` for `coherent.build` might already have satisfied dependencies used by the `.pypi` module, so those won't appear in the new project. All the more reason to get dependency inference working.

**Comment by jaraco** [comment]
In 403266d, `inferred_deps` now makes the test and docs dependencies optional.

**Comment by jaraco** [comment]
In 78f62ed35e6b49ee0e5a56fcfe07b2a7b249dd10, I've added a `combined_deps` function that combines the inferred and declared dependencies, giving the declared ones precedence.

**Comment by jaraco** [comment]
With this latest code, I'm able to remove most of the declared dependencies, and the `combined_deps` still produces the same list.

```
 coherent.build feature/import-detection 🐚 py -c "from coherent.build import discovery; print(sorted(discovery.read_deps()))"
['build', 'git-fame', 'importlib_resources; python_version < "3.12"', 'jaraco.collections', 'jaraco.compat>=4.1', 'jaraco.context', 'jaraco.functools', 'jaraco.mongodb', 'jaraco.ui', 'jaraco.vcs', 'keyring', 'more-itertools', 'packaging', 'pip-run', 'requests', 'requests-file', 'requests_toolbelt', 'retry-requests', 'setuptools_scm', 'tempora', 'tqdm', 'wheel', 'zipp>=3.20']
 coherent.build feature/import-detection 🐚 py -c "from coherent.build import discovery; print(sorted(discovery.combined_deps()))"
['build', 'git-fame', 'importlib_resources; python_version < "3.12"', 'jaraco.collections', 'jaraco.compat>=4.1', 'jaraco.context', 'jaraco.functools', 'jaraco.mongodb', 'jaraco.ui', 'jaraco.vcs', 'keyring', 'more-itertools', 'packaging', 'pip-run', 'requests', 'requests-file', 'requests_toolbelt', 'retry-requests', 'setuptools_scm', 'tempora', 'tqdm', 'wheel', 'zipp>=3.20']
 coherent.build feature/import-detection 🐚 git stash pop
...
 coherent.build feature/import-detection 🐚 git diff
diff --git a/__init__.py b/__init__.py
index 632a763..3a0b1d1 100644
--- a/__init__.py
+++ b/__init__.py
@@ -1,27 +1,9 @@
 __requires__ = [
-    'wheel',
-    'pip-run',
-    'setuptools_scm',
     'build',
     'git-fame',
-    'jaraco.context',
-    'requests',
-    'packaging',
-    'jaraco.functools',
     'jaraco.compat >= 4.1',
     'importlib_resources; python_version < "3.12"',
-    'jaraco.vcs',
-    'requests_toolbelt',
     'zipp>=3.20',
-    'jaraco.mongodb',
-    'keyring',
-    'tempora',
-    'requests-file',
-    'tqdm',
-    'retry-requests',
-    'jaraco.ui',
-    'more-itertools',
-    'jaraco.collections',
 ]
 
 
 coherent.build feature/import-detection 🐚 py -c "from coherent.build import discovery; print(sorted(discovery.combined_deps()))"
['build', 'git-fame', 'importlib_resources; python_version < "3.12"', 'jaraco.collections', 'jaraco.compat>=4.1', 'jaraco.context', 'jaraco.functools', 'jaraco.mongodb', 'jaraco.ui', 'jaraco.vcs', 'keyring', 'more-itertools', 'packaging', 'pip-run', 'requests', 'requests-file', 'requests-toolbelt', 'retry-requests', 'setuptools-scm', 'tempora', 'tqdm', 'wheel', 'zipp>=3.20']
```

While working on this issue, I discovered two missing dependencies, one for `jaraco.collections` and the other for `more-itertools`.

You'll note that I had to keep `build` and `git-fame`, because those are invoked through subprocesses and not imports. I also had to keep declarations for `jaraco.compat`, `importlib_resources`, and `zipp` because they have specific pins.

But I dare say, this feature is working as intended for a non-trivial use-case.

At this point, all that's left to do is decide how to organize the functionality (which projects) and test some other projects.

**Comment by jaraco** [comment]
I've extracted the commits for the code to [coherent.deps](/coherent-oss/coherent.deps) and I'm going to re-write this branch to only include not those changes. To get the changes I wanted, I ran this command:

```
git filter-repo --path distributions/load.py --path distributions/process.py --path imports.py --path pypi.py --path load-distributions.py --path process-distributions.py --path top-distributions.py --force
```

(I used the output of `git filter-repo --analyze` to figure out which paths to include (honoring renames).

Next, I'll do the inverse of that and rebase those changes atop main. In the meantime, I'm archiving the combined history to `refs/archive/import-detection-combined`.

**Comment by jaraco** [comment]
In https://github.com/coherent-oss/coherent.build/actions/runs/10641536353/job/29502812454, I'm seeing an unexpected failure.

```
________________ [doctest] coherent.build.discovery.extra_for _________________
185 
186     Emit appropriate extra marker if relevant to the module's path.
187 
188     >>> extra_for(pathlib.Path('foo/bar'))
189     ''
190     >>> extra_for(pathlib.Path('foo.py'))
191     ''
192     >>> extra_for(pathlib.Path('tests/foo'))
Expected:
    '; extra=="test"'
Got:
    ''

D:\a\coherent.build\coherent.build\discovery.py:192: DocTestFailure
```

But when I go to Windows, the output is what I expect:

```
 🐚 py -3.12
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> str(pathlib.Path('tests/foo').parents[-2])
'tests'
```

How then are the tests failing, given the implementation?

https://github.com/coherent-oss/coherent.build/blob/9492957aad8b94fe62d595181ba1a1bcfbe8bee3/discovery.py#L197-L201

**Comment by jaraco** [comment]
Even weirder, that test passes for me on my Windows machine.

```
 coherent.build feature/import-detection [1] 🐚 coh test -k extra_for
===================================================== test session starts ======================================================
platform win32 -- Python 3.12.2, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\jaraco\code\coherent-oss\coherent.build
configfile: pyproject.toml
plugins: jaraco.mongodb-12.1.1, jaraco.vcs-2.4.0, typeguard-4.3.0, coherent.test-0.7.0
collected 15 items / 14 deselected / 1 selected

discovery.py .                                                                                                            [100%] 

=============================================== 1 passed, 14 deselected in 0.09s ===============================================
```

What's going on?

**Comment by jaraco** [comment]
Okay. There are at least two issues. First, on older Pythons, `.parents` behaves differently:

```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> pathlib.Path('tests/foo').parents[-2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\pathlib.py", line 621, in __getitem__
    raise IndexError(idx)
IndexError: -2
>>> list(pathlib.Path('tests/foo').parents)
[WindowsPath('tests'), WindowsPath('.')]
>>> list(pathlib.Path('tests/foo').parents)[-2]
WindowsPath('tests')
```

Also, although the job advertises it's targeting Python 3.12, it's actually on Python 3.9.

![image](https://github.com/user-attachments/assets/1f4c18f6-9fd2-4e16-9c35-a644d19ecf1f)

It appears I can work around the pathlib issue by wrapping parents in a list.

**Comment by jaraco** [comment]
The Gemini-backed experiment discussed above (8b577b2, 909ce57) lived on the `feature/genai-imports` branch, which is now archived as `refs/archive/feature/genai-imports` and removed from the branch list:

```
git fetch origin refs/archive/feature/genai-imports
```

Recording it here so those commits stay reachable. The approach this issue settled on instead — static AST extraction plus a PyPI top-level-name mapping — shipped as `coherent.deps.imports` and `coherent.deps.pypi`, which `discovery.py` uses today.
